### ISSUE TITLE
never-pairo requires a domain

### ISSUE THREAD

**Issue by eholk** [calvis/cKanren#3]
```
> (run 1 (q) (never-pairo q))

Exception in verify-all-bound: Constrained variable ~s without domain with irritant #(q)
Type (debug) to enter the debugger.
```

You dun goofed.

**Comment by dfried00** [comment]
So change your version.
I will pass this along to Claire.

...Dan

On Thu, Jan 12, 2012 at 4:04 PM, Eric Holk <
reply@reply.github.com

**Comment by calvis** [comment]
Fixed with [this commit](https://github.com/calvis/cKanren/commit/77e2712d5dfcab222e14475775ec6ef39f9b79b2). Code needs some cleanup but it should work now.
